-- MySQL Script generated by MySQL Workbench
-- 07/03/19 13:14:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_rutinas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_rutinas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_rutinas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bd_rutinas` ;

-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_UCS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_UCS` (
  `ID_UCS` INT NOT NULL AUTO_INCREMENT,
  `NUMERO_UCS` CHAR(5) NULL,
  `IMPR IFV-1` CHAR(2) NULL,
  PRIMARY KEY (`ID_UCS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_SDD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_SDD` (
  `ID_SDD` INT NOT NULL AUTO_INCREMENT,
  `ESTADO` CHAR(2) NULL,
  `LAN_1` CHAR(1) NULL,
  `LAN_2` CHAR(1) NULL,
  `TBL_UCS_ID_UCS` INT NOT NULL,
  PRIMARY KEY (`ID_SDD`),
  INDEX `fk_TBL_SDD_TBL_UCS_idx` (`TBL_UCS_ID_UCS` ASC),
  CONSTRAINT `fk_TBL_SDD_TBL_UCS`
    FOREIGN KEY (`TBL_UCS_ID_UCS`)
    REFERENCES `bd_rutinas`.`TBL_UCS` (`ID_UCS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_EMPLEADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_EMPLEADOS` (
  `ID_EMPLEADO` INT UNSIGNED NOT NULL,
  `NOMBRE` INT NULL,
  `CORREO` VARCHAR(45) NULL,
  `TELEFONO_FIJO` VARCHAR(45) NULL,
  `TELEFONO_MOVIL` VARCHAR(45) NULL,
  `TBL_CARGOS_ID_CARGO` INT NOT NULL,
  `TBL_UCS_ID_UCS` INT NOT NULL,
  PRIMARY KEY (`ID_EMPLEADO`),
  INDEX `fk_TBL_EMPLEADOS_TBL_UCS1_idx` (`TBL_UCS_ID_UCS` ASC),
  CONSTRAINT `fk_TBL_EMPLEADOS_TBL_UCS1`
    FOREIGN KEY (`TBL_UCS_ID_UCS`)
    REFERENCES `bd_rutinas`.`TBL_UCS` (`ID_UCS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_BITACORA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_BITACORA` (
  `ID_BITACORA` INT NOT NULL,
  `FECHA` DATE NULL,
  `NOMBRE_FORMULARIO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_BITACORA`),
  CONSTRAINT `ID_EMPLEADO_FK`
    FOREIGN KEY ()
    REFERENCES `bd_rutinas`.`TBL_EMPLEADOS` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
