-- MySQL Script generated by MySQL Workbench
-- Mon Nov 25 18:57:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_rutinas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_rutinas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_rutinas` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema bd_whatsapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_whatsapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_whatsapp` DEFAULT CHARACTER SET latin1 ;
USE `bd_rutinas` ;

-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_CARGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_CARGOS` (
  `ID_CARGO` INT NOT NULL,
  `NOMBRE_CARGO` VARCHAR(45) NULL,
  `PERMISOS_CARGO` VARCHAR(100) NULL,
  PRIMARY KEY (`ID_CARGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_PAISES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_PAISES` (
  `ID_PAIS` INT NOT NULL AUTO_INCREMENT,
  `PAIS` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_PAIS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_CIUDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_CIUDADES` (
  `ID_CIUDAD` INT NOT NULL AUTO_INCREMENT,
  `ID_PAIS` INT NOT NULL,
  `NOMBRE_CIUDAD` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_CIUDAD`),
  INDEX `fk_TBL_CIUDADES_TBL_PAISES1_idx` (`ID_PAIS` ASC) VISIBLE,
  UNIQUE INDEX `NOMBRE_CIUDAD_UNIQUE` (`NOMBRE_CIUDAD` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_CIUDADES_TBL_PAISES1`
    FOREIGN KEY (`ID_PAIS`)
    REFERENCES `bd_rutinas`.`TBL_PAISES` (`ID_PAIS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_SITIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_SITIOS` (
  `ID_SITIO` INT NOT NULL AUTO_INCREMENT,
  `ID_CIUDAD` INT NOT NULL,
  `NOMBRE_SITIO` VARCHAR(45) NULL,
  `TRILITERAL` VARCHAR(30) NULL,
  PRIMARY KEY (`ID_SITIO`),
  INDEX `fk_TBL_SITIOS_TBL_CIUDADES1_idx` (`ID_CIUDAD` ASC) VISIBLE,
  UNIQUE INDEX `ID_SITIO_UNIQUE` (`ID_SITIO` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_SITIOS_TBL_CIUDADES1`
    FOREIGN KEY (`ID_CIUDAD`)
    REFERENCES `bd_rutinas`.`TBL_CIUDADES` (`ID_CIUDAD`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_UNIDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_UNIDADES` (
  `ID_UNIDAD` INT NOT NULL AUTO_INCREMENT,
  `ID_PAIS` INT NOT NULL,
  `ID_SITIO` INT NOT NULL,
  `NOMBRE_UNIDAD` VARCHAR(45) NULL,
  `DESCRIPCION_UNIDAD` VARCHAR(300) NULL,
  PRIMARY KEY (`ID_UNIDAD`),
  INDEX `fk_TBL_UNIDADES_TBL_SITIOS2_idx` (`ID_SITIO` ASC) VISIBLE,
  INDEX `fk_TBL_UNIDADES_TBL_PAISES1_idx` (`ID_PAIS` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_UNIDADES_TBL_SITIOS2`
    FOREIGN KEY (`ID_SITIO`)
    REFERENCES `bd_rutinas`.`TBL_SITIOS` (`ID_SITIO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TBL_UNIDADES_TBL_PAISES1`
    FOREIGN KEY (`ID_PAIS`)
    REFERENCES `bd_rutinas`.`TBL_PAISES` (`ID_PAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_MANTENIMIENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_MANTENIMIENTOS` (
  `ID_MANTENIMIENTO` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TITULO_MANTENIMIENTO` VARCHAR(100) NULL,
  `DESCRIPCION_MANTENIMIENTO` VARCHAR(200) NULL,
  `FECHA_CREACION` DATETIME NULL,
  `FECHA_LIMITE` DATETIME NULL,
  PRIMARY KEY (`ID_MANTENIMIENTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_EMPLEADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_EMPLEADOS` (
  `ID_EMPLEADO` INT NOT NULL AUTO_INCREMENT,
  `ID_PAIS` INT NOT NULL,
  `ID_UNIDAD` INT NOT NULL,
  `ID_CARGO` INT NOT NULL,
  `ID_MANTENIMIENTO` INT UNSIGNED NOT NULL,
  `NOMBRE` VARCHAR(100) NULL,
  `CORREO` VARCHAR(45) NULL,
  `USUARIO` VARCHAR(45) NULL,
  `CONTRASENA` VARCHAR(45) NULL,
  `ACCESO` TINYINT(1) NULL,
  PRIMARY KEY (`ID_EMPLEADO`),
  INDEX `fk_TBL_EMPLEADOS_TBL_CARGOS1_idx` (`ID_CARGO` ASC) VISIBLE,
  INDEX `fk_TBL_EMPLEADOS_TBL_UNIDADES1_idx` (`ID_UNIDAD` ASC) VISIBLE,
  INDEX `fk_TBL_EMPLEADOS_TBL_MANTENIMIENTOS1_idx` (`ID_MANTENIMIENTO` ASC) VISIBLE,
  INDEX `fk_TBL_EMPLEADOS_TBL_PAISES1_idx` (`ID_PAIS` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_EMPLEADOS_TBL_CARGOS1`
    FOREIGN KEY (`ID_CARGO`)
    REFERENCES `bd_rutinas`.`TBL_CARGOS` (`ID_CARGO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TBL_EMPLEADOS_TBL_UNIDADES1`
    FOREIGN KEY (`ID_UNIDAD`)
    REFERENCES `bd_rutinas`.`TBL_UNIDADES` (`ID_UNIDAD`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TBL_EMPLEADOS_TBL_MANTENIMIENTOS1`
    FOREIGN KEY (`ID_MANTENIMIENTO`)
    REFERENCES `bd_rutinas`.`TBL_MANTENIMIENTOS` (`ID_MANTENIMIENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_EMPLEADOS_TBL_PAISES1`
    FOREIGN KEY (`ID_PAIS`)
    REFERENCES `bd_rutinas`.`TBL_PAISES` (`ID_PAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_BITACORA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_BITACORA` (
  `ID_BITACORA` INT NOT NULL AUTO_INCREMENT,
  `ID_EMPLEADO` INT NOT NULL,
  `FECHA_REALIZADA` TIMESTAMP NULL,
  `NOMBRE_FORMULARIO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_BITACORA`),
  INDEX `fk_TBL_BITACORA_TBL_EMPLEADOS1_idx` (`ID_EMPLEADO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_SISTEMAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_SISTEMAS` (
  `ID_SISTEMA` INT NOT NULL AUTO_INCREMENT,
  `ID_UNIDAD` INT NOT NULL,
  `NOMBRE_SISTEMA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_SISTEMA`),
  INDEX `fk_TBL_SISTEMAS_TBL_UNIDADES1_idx` (`ID_UNIDAD` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_SISTEMAS_TBL_UNIDADES1`
    FOREIGN KEY (`ID_UNIDAD`)
    REFERENCES `bd_rutinas`.`TBL_UNIDADES` (`ID_UNIDAD`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_HISTORIAL_ACCESOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_HISTORIAL_ACCESOS` (
  `ID_EMPLEADO` INT NOT NULL,
  `FECHA_HORA_ACCESO` DATETIME NULL,
  INDEX `fk_TBL_HISTORIAL_ACCESOS_TBL_EMPLEADOS1_idx` (`ID_EMPLEADO` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_HISTORIAL_ACCESOS_TBL_EMPLEADOS1`
    FOREIGN KEY (`ID_EMPLEADO`)
    REFERENCES `bd_rutinas`.`TBL_EMPLEADOS` (`ID_EMPLEADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_SUBSISTEMAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_SUBSISTEMAS` (
  `ID_SUBSISTEMA` INT NOT NULL AUTO_INCREMENT,
  `ID_SISTEMA` INT NOT NULL,
  `NOMBRE_SUBSISTEMA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_SUBSISTEMA`),
  INDEX `fk_TBL_SUBSISTEMAS_TBL_SISTEMAS1_idx` (`ID_SISTEMA` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_SUBSISTEMAS_TBL_SISTEMAS1`
    FOREIGN KEY (`ID_SISTEMA`)
    REFERENCES `bd_rutinas`.`TBL_SISTEMAS` (`ID_SISTEMA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_FORMATOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_FORMATOS` (
  `ID_FORMATO` INT NOT NULL,
  `ID_SISTEMA` INT NOT NULL,
  `NOMBRE_FORMATO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_FORMATO`),
  INDEX `fk_TBL_FORMATOS_TBL_SISTEMAS1_idx` (`ID_SISTEMA` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_FORMATOS_TBL_SISTEMAS1`
    FOREIGN KEY (`ID_SISTEMA`)
    REFERENCES `bd_rutinas`.`TBL_SISTEMAS` (`ID_SISTEMA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_EQUIPOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_EQUIPOS` (
  `ID_EQUIPO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_EQUIPO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_EQUIPO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_COMPONENTE_FINAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_COMPONENTE_FINAL` (
  `ID_COMPONENTE` INT NULL AUTO_INCREMENT,
  `ID_EQUIPO` INT NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL,
  PRIMARY KEY (`ID_COMPONENTE`),
  INDEX `fk_TBL_SUB_EQUIPOS_TBL_EQUIPOS1_idx` (`ID_EQUIPO` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_SUB_EQUIPOS_TBL_EQUIPOS1`
    FOREIGN KEY (`ID_EQUIPO`)
    REFERENCES `bd_rutinas`.`TBL_EQUIPOS` (`ID_EQUIPO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_LISTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_LISTAS` (
  `SUBTIPO_VALOR_LISTA` VARCHAR(10) NOT NULL,
  `VALOR_CADENA` VARCHAR(45) NULL,
  PRIMARY KEY (`SUBTIPO_VALOR_LISTA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_BOOLEANOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_BOOLEANOS` (
  `SUBTIPO_VALOR_BOOLEANO` VARCHAR(10) NOT NULL,
  `VALOR_CADENA` VARCHAR(10) NULL,
  PRIMARY KEY (`SUBTIPO_VALOR_BOOLEANO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_ENTEROS_FLOTANTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_ENTEROS_FLOTANTES` (
  `SUBTIPO_VALOR_NUMERO` INT NOT NULL AUTO_INCREMENT,
  `VALOR_MINIMO` FLOAT NULL,
  `VALOR_MAXIMO` FLOAT NULL,
  PRIMARY KEY (`SUBTIPO_VALOR_NUMERO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_MASTER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_MASTER` (
  `ID_DATO_INSERTADO` INT NOT NULL AUTO_INCREMENT,
  `ID_EQUIPO` INT NOT NULL,
  `ID_COMPONENTE_FINAL` INT NULL,
  `ID_EMPLEADO` INT NOT NULL,
  `FECHA_AUTOMATICA` DATETIME NULL DEFAULT NOW(),
  `SUBTIPO_VALOR_BOOLEANO` VARCHAR(10) NULL,
  `SUBTIPO_VALOR_LISTA` VARCHAR(10) NULL,
  `SUBTIPO_VALOR_NUMERO` INT NULL,
  `DATO_NUMERICO_OBTENIDO` VARCHAR(45) NULL,
  INDEX `fk_TBL_MASTER_TBL_EQUIPOS1_idx` (`ID_EQUIPO` ASC) VISIBLE,
  INDEX `fk_TBL_MASTER_TBL_COMPONENTE_FINAL1_idx` (`ID_COMPONENTE_FINAL` ASC) VISIBLE,
  INDEX `fk_TBL_MASTER_TBL_LISTAS1_idx` (`SUBTIPO_VALOR_LISTA` ASC) VISIBLE,
  INDEX `fk_TBL_MASTER_TBL_BOOLEANOS1_idx` (`SUBTIPO_VALOR_BOOLEANO` ASC) VISIBLE,
  PRIMARY KEY (`ID_DATO_INSERTADO`),
  INDEX `fk_TBL_MASTER_TBL_ENTEROS_FLOTANTES1_idx` (`SUBTIPO_VALOR_NUMERO` ASC) VISIBLE,
  INDEX `fk_TBL_MASTER_TBL_EMPLEADOS2_idx` (`ID_EMPLEADO` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_MASTER_TBL_EQUIPOS1`
    FOREIGN KEY (`ID_EQUIPO`)
    REFERENCES `bd_rutinas`.`TBL_EQUIPOS` (`ID_EQUIPO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TBL_MASTER_TBL_COMPONENTE_FINAL1`
    FOREIGN KEY (`ID_COMPONENTE_FINAL`)
    REFERENCES `bd_rutinas`.`TBL_COMPONENTE_FINAL` (`ID_COMPONENTE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TBL_MASTER_TBL_LISTAS1`
    FOREIGN KEY (`SUBTIPO_VALOR_LISTA`)
    REFERENCES `bd_rutinas`.`TBL_LISTAS` (`SUBTIPO_VALOR_LISTA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TBL_MASTER_TBL_BOOLEANOS1`
    FOREIGN KEY (`SUBTIPO_VALOR_BOOLEANO`)
    REFERENCES `bd_rutinas`.`TBL_BOOLEANOS` (`SUBTIPO_VALOR_BOOLEANO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TBL_MASTER_TBL_ENTEROS_FLOTANTES1`
    FOREIGN KEY (`SUBTIPO_VALOR_NUMERO`)
    REFERENCES `bd_rutinas`.`TBL_ENTEROS_FLOTANTES` (`SUBTIPO_VALOR_NUMERO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_MASTER_TBL_EMPLEADOS2`
    FOREIGN KEY (`ID_EMPLEADO`)
    REFERENCES `bd_rutinas`.`TBL_EMPLEADOS` (`ID_EMPLEADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_EQUIPOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_EQUIPOS` (
  `ID_EQUIPO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_EQUIPO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_EQUIPO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_LOCALIDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_LOCALIDADES` (
  `ID_LOCALIDAD` INT NOT NULL AUTO_INCREMENT,
  `ID_PAIS` INT NOT NULL,
  `ID_SITIO` INT NOT NULL,
  `NOMBRE_LOCALIDAD` VARCHAR(45) NULL,
  `TRILITERAL` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_LOCALIDAD`),
  INDEX `fk_TBL_LOCALIDADES_TBL_SITIOS1_idx` (`ID_SITIO` ASC) VISIBLE,
  INDEX `fk_TBL_LOCALIDADES_TBL_PAISES1_idx` (`ID_PAIS` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_LOCALIDADES_TBL_SITIOS1`
    FOREIGN KEY (`ID_SITIO`)
    REFERENCES `bd_rutinas`.`TBL_SITIOS` (`ID_SITIO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TBL_LOCALIDADES_TBL_PAISES1`
    FOREIGN KEY (`ID_PAIS`)
    REFERENCES `bd_rutinas`.`TBL_PAISES` (`ID_PAIS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_SUBUNIDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_SUBUNIDADES` (
  `ID_SUBUNIDAD` INT NOT NULL AUTO_INCREMENT,
  `ID_UNIDAD` INT NOT NULL,
  `NOMBRE_SUBUNIDAD` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_SUBUNIDAD`),
  INDEX `fk_TBL_SUBUNIDADES_TBL_UNIDADES1_idx` (`ID_UNIDAD` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_SUBUNIDADES_TBL_UNIDADES1`
    FOREIGN KEY (`ID_UNIDAD`)
    REFERENCES `bd_rutinas`.`TBL_UNIDADES` (`ID_UNIDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_SITIOS_has_TBL_SISTEMAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_SITIOS_has_TBL_SISTEMAS` (
  `ID_SITIO` INT NOT NULL,
  `ID_SISTEMA` INT NOT NULL,
  PRIMARY KEY (`ID_SITIO`, `ID_SISTEMA`),
  INDEX `fk_TBL_SITIOS_has_TBL_SISTEMAS_TBL_SISTEMAS1_idx` (`ID_SISTEMA` ASC) VISIBLE,
  INDEX `fk_TBL_SITIOS_has_TBL_SISTEMAS_TBL_SITIOS1_idx` (`ID_SITIO` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_SITIOS_has_TBL_SISTEMAS_TBL_SITIOS1`
    FOREIGN KEY (`ID_SITIO`)
    REFERENCES `bd_rutinas`.`TBL_SITIOS` (`ID_SITIO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TBL_SITIOS_has_TBL_SISTEMAS_TBL_SISTEMAS1`
    FOREIGN KEY (`ID_SISTEMA`)
    REFERENCES `bd_rutinas`.`TBL_SISTEMAS` (`ID_SISTEMA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_cargos` (
  `ID_CARGO` INT(11) NOT NULL,
  `NOMBRE_CARGO` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CARGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_paises` (
  `ID_PAIS` INT(11) NOT NULL AUTO_INCREMENT,
  `PAIS` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PAIS`))
ENGINE = InnoDB
AUTO_INCREMENT = 1346
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_ciudades` (
  `ID_CIUDAD` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_PAIS` INT(11) NOT NULL,
  `NOMBRE_CIUDAD` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CIUDAD`),
  UNIQUE INDEX `NOMBRE_CIUDAD_UNIQUE` (`NOMBRE_CIUDAD` ASC) VISIBLE,
  INDEX `fk_TBL_CIUDADES_TBL_PAISES1_idx` (`ID_PAIS` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_CIUDADES_TBL_PAISES1`
    FOREIGN KEY (`ID_PAIS`)
    REFERENCES `bd_rutinas`.`tbl_paises` (`ID_PAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_sitios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_sitios` (
  `ID_SITIO` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_CIUDAD` INT(11) NOT NULL,
  `NOMBRE_SITIO` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_SITIO`),
  INDEX `fk_TBL_SITIOS_TBL_CIUDADES1_idx` (`ID_CIUDAD` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_SITIOS_TBL_CIUDADES1`
    FOREIGN KEY (`ID_CIUDAD`)
    REFERENCES `bd_rutinas`.`tbl_ciudades` (`ID_CIUDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_unidades` (
  `ID_UNIDAD` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_SITIO` INT(11) NOT NULL,
  `NOMBRE_UNIDAD` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_UNIDAD`),
  INDEX `fk_TBL_UNIDADES_TBL_SITIOS1_idx` (`ID_SITIO` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_UNIDADES_TBL_SITIOS1`
    FOREIGN KEY (`ID_SITIO`)
    REFERENCES `bd_rutinas`.`tbl_sitios` (`ID_SITIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_empleados` (
  `ID_EMPLEADO` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_UNIDAD` INT(11) NOT NULL,
  `ID_CARGO` INT(11) NOT NULL,
  `NOMBRE` VARCHAR(100) NULL DEFAULT NULL,
  `CORREO` VARCHAR(45) NULL DEFAULT NULL,
  `USUARIO` VARCHAR(45) NULL DEFAULT NULL,
  `CONTRASENA` VARCHAR(45) NULL DEFAULT NULL,
  `ACCESO` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_EMPLEADO`),
  INDEX `fk_TBL_EMPLEADOS_TBL_CARGOS1_idx` (`ID_CARGO` ASC) VISIBLE,
  INDEX `fk_TBL_EMPLEADOS_TBL_UNIDADES1_idx` (`ID_UNIDAD` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_EMPLEADOS_TBL_CARGOS1`
    FOREIGN KEY (`ID_CARGO`)
    REFERENCES `bd_rutinas`.`tbl_cargos` (`ID_CARGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_EMPLEADOS_TBL_UNIDADES1`
    FOREIGN KEY (`ID_UNIDAD`)
    REFERENCES `bd_rutinas`.`tbl_unidades` (`ID_UNIDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_bitacora` (
  `ID_BITACORA` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_EMPLEADO` INT(11) NOT NULL,
  `FECHA_REALIZADA` TIMESTAMP NULL DEFAULT NULL,
  `NOMBRE_FORMULARIO` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_BITACORA`),
  INDEX `fk_TBL_BITACORA_TBL_EMPLEADOS1_idx` (`ID_EMPLEADO` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_BITACORA_TBL_EMPLEADOS1`
    FOREIGN KEY (`ID_EMPLEADO`)
    REFERENCES `bd_rutinas`.`tbl_empleados` (`ID_EMPLEADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_sistemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_sistemas` (
  `ID_SISTEMA` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_UNIDAD` INT(11) NOT NULL,
  `NOMBRE_SISTEMA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_SISTEMA`),
  INDEX `fk_TBL_SISTEMAS_TBL_UNIDADES1_idx` (`ID_UNIDAD` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_SISTEMAS_TBL_UNIDADES1`
    FOREIGN KEY (`ID_UNIDAD`)
    REFERENCES `bd_rutinas`.`tbl_unidades` (`ID_UNIDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_subsistemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_subsistemas` (
  `ID_SUBSISTEMA` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_SISTEMA` INT(11) NOT NULL,
  `NOMBRE_SUBSISTEMA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_SUBSISTEMA`),
  INDEX `fk_TBL_SUBSISTEMAS_TBL_SISTEMAS1_idx` (`ID_SISTEMA` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_SUBSISTEMAS_TBL_SISTEMAS1`
    FOREIGN KEY (`ID_SISTEMA`)
    REFERENCES `bd_rutinas`.`tbl_sistemas` (`ID_SISTEMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_equipos` (
  `ID_EQUIPO` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_SUBSISTEMA` INT(11) NOT NULL,
  `NOMBRE_EQUIPO` VARCHAR(45) NULL DEFAULT NULL,
  `UBICACION_FISICA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_EQUIPO`),
  INDEX `fk_TBL_EQUIPOS_TBL_SUBSISTEMAS1_idx` (`ID_SUBSISTEMA` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_EQUIPOS_TBL_SUBSISTEMAS1`
    FOREIGN KEY (`ID_SUBSISTEMA`)
    REFERENCES `bd_rutinas`.`tbl_subsistemas` (`ID_SUBSISTEMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_componente_final`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_componente_final` (
  `ID_COMPONENTE` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_EQUIPO` INT(11) NOT NULL,
  `DESCRIPCION` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_COMPONENTE`),
  INDEX `fk_TBL_SUB_EQUIPOS_TBL_EQUIPOS1_idx` (`ID_EQUIPO` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_SUB_EQUIPOS_TBL_EQUIPOS1`
    FOREIGN KEY (`ID_EQUIPO`)
    REFERENCES `bd_rutinas`.`tbl_equipos` (`ID_EQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_formatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_formatos` (
  `ID_FORMATO` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_SISTEMA` INT(11) NOT NULL,
  `NOMBRE_FORMATO` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_FORMATO`),
  INDEX `fk_TBL_FORMATOS_TBL_SISTEMAS1_idx` (`ID_SISTEMA` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_FORMATOS_TBL_SISTEMAS1`
    FOREIGN KEY (`ID_SISTEMA`)
    REFERENCES `bd_rutinas`.`tbl_sistemas` (`ID_SISTEMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_localidades` (
  `ID_LOCALIDAD` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_SITIO` INT(11) NOT NULL,
  `NOMBRE_LOCALIDAD` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_LOCALIDAD`),
  INDEX `fk_TBL_LOCALIDADES_TBL_SITIOS1_idx` (`ID_SITIO` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_LOCALIDADES_TBL_SITIOS1`
    FOREIGN KEY (`ID_SITIO`)
    REFERENCES `bd_rutinas`.`tbl_sitios` (`ID_SITIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_master` (
  `ID_MASTER` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_EMPLEADO` INT(11) NOT NULL,
  `ID_SITIO` INT(11) NOT NULL,
  `ID_FORMATO` INT(11) NOT NULL,
  `ID_DEF_PARAMETRO` INT(11) NOT NULL,
  `ID_VALOR` INT(11) NOT NULL,
  `ID_SISTEMA` INT(11) NOT NULL,
  `ID_COMPONENTE` INT(11) NOT NULL,
  `ID_EQUIPO` INT(11) NOT NULL,
  `MASTER_VALOR` VARCHAR(45) NULL DEFAULT NULL,
  `FECHA_AUTOMATICA` DATETIME NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID_MASTER`),
  INDEX `fk_TBL_MASTER_TBL_SISTEMAS1_idx` (`ID_SISTEMA` ASC) VISIBLE,
  INDEX `fk_TBL_MASTER_TBL_EQUIPOS1_idx` (`ID_EQUIPO` ASC) VISIBLE,
  INDEX `fk_TBL_MASTER_TBL_DEFINICION_PARAMETROS1_idx` (`ID_DEF_PARAMETRO` ASC) VISIBLE,
  INDEX `fk_TBL_MASTER_TBL_DICCIONARIO1_idx` (`ID_VALOR` ASC) VISIBLE,
  INDEX `fk_TBL_MASTER_TBL_SITIOS1_idx` (`ID_SITIO` ASC) VISIBLE,
  INDEX `fk_TBL_MASTER_TBL_COMPONENTE_FINAL1_idx` (`ID_COMPONENTE` ASC) VISIBLE,
  INDEX `fk_TBL_MASTER_TBL_FORMATOS1_idx` (`ID_FORMATO` ASC) VISIBLE,
  INDEX `fk_TBL_MASTER_TBL_EMPLEADOS1_idx` (`ID_EMPLEADO` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_MASTER_TBL_COMPONENTE_FINAL1`
    FOREIGN KEY (`ID_COMPONENTE`)
    REFERENCES `bd_rutinas`.`tbl_componente_final` (`ID_COMPONENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_MASTER_TBL_EMPLEADOS1`
    FOREIGN KEY (`ID_EMPLEADO`)
    REFERENCES `bd_rutinas`.`tbl_empleados` (`ID_EMPLEADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_MASTER_TBL_EQUIPOS1`
    FOREIGN KEY (`ID_EQUIPO`)
    REFERENCES `bd_rutinas`.`tbl_equipos` (`ID_EQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_MASTER_TBL_FORMATOS1`
    FOREIGN KEY (`ID_FORMATO`)
    REFERENCES `bd_rutinas`.`tbl_formatos` (`ID_FORMATO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_MASTER_TBL_SISTEMAS1`
    FOREIGN KEY (`ID_SISTEMA`)
    REFERENCES `bd_rutinas`.`tbl_sistemas` (`ID_SISTEMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_MASTER_TBL_SITIOS1`
    FOREIGN KEY (`ID_SITIO`)
    REFERENCES `bd_rutinas`.`tbl_sitios` (`ID_SITIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_sitios_has_tbl_sistemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_sitios_has_tbl_sistemas` (
  `ID_SITIO` INT(11) NOT NULL,
  `ID_SISTEMA` INT(11) NOT NULL,
  PRIMARY KEY (`ID_SITIO`, `ID_SISTEMA`),
  INDEX `fk_TBL_SITIOS_has_TBL_SISTEMAS_TBL_SISTEMAS1_idx` (`ID_SISTEMA` ASC) VISIBLE,
  INDEX `fk_TBL_SITIOS_has_TBL_SISTEMAS_TBL_SITIOS1_idx` (`ID_SITIO` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_SITIOS_has_TBL_SISTEMAS_TBL_SISTEMAS1`
    FOREIGN KEY (`ID_SISTEMA`)
    REFERENCES `bd_rutinas`.`tbl_sistemas` (`ID_SISTEMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_SITIOS_has_TBL_SISTEMAS_TBL_SITIOS1`
    FOREIGN KEY (`ID_SITIO`)
    REFERENCES `bd_rutinas`.`tbl_sitios` (`ID_SITIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`tbl_subunidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`tbl_subunidades` (
  `ID_SUBUNIDAD` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_UNIDAD` INT(11) NOT NULL,
  `NOMBRE_SUBUNIDAD` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_SUBUNIDAD`),
  INDEX `fk_TBL_SUBUNIDADES_TBL_UNIDADES1_idx` (`ID_UNIDAD` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_SUBUNIDADES_TBL_UNIDADES1`
    FOREIGN KEY (`ID_UNIDAD`)
    REFERENCES `bd_rutinas`.`tbl_unidades` (`ID_UNIDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_AREAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_AREAS` (
  `ID_AREA` INT NOT NULL AUTO_INCREMENT,
  `ID_UNIDAD` INT NOT NULL,
  `ID_AREA_SUPERIOR` INT NULL,
  `NOMBRE_AREA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_AREA`),
  INDEX `fk_TBL_AREAS_TBL_UNIDADES1_idx` (`ID_UNIDAD` ASC) VISIBLE,
  INDEX `fk_TBL_AREAS_TBL_AREAS1_idx` (`ID_AREA_SUPERIOR` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_AREAS_TBL_UNIDADES1`
    FOREIGN KEY (`ID_UNIDAD`)
    REFERENCES `bd_rutinas`.`TBL_UNIDADES` (`ID_UNIDAD`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TBL_AREAS_TBL_AREAS1`
    FOREIGN KEY (`ID_AREA_SUPERIOR`)
    REFERENCES `bd_rutinas`.`TBL_AREAS` (`ID_AREA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_EMPLEADOS_has_TBL_MANTENIMIENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_EMPLEADOS_has_TBL_MANTENIMIENTOS` (
  `ID_EMPLEADO` INT NOT NULL,
  `ID_MANTENIMIENTO` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_EMPLEADO`, `ID_MANTENIMIENTO`),
  INDEX `fk_TBL_EMPLEADOS_has_TBL_MANTENIMIENTOS_TBL_MANTENIMIENTOS1_idx` (`ID_MANTENIMIENTO` ASC) VISIBLE,
  INDEX `fk_TBL_EMPLEADOS_has_TBL_MANTENIMIENTOS_TBL_EMPLEADOS1_idx` (`ID_EMPLEADO` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_EMPLEADOS_has_TBL_MANTENIMIENTOS_TBL_EMPLEADOS1`
    FOREIGN KEY (`ID_EMPLEADO`)
    REFERENCES `bd_rutinas`.`TBL_EMPLEADOS` (`ID_EMPLEADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_EMPLEADOS_has_TBL_MANTENIMIENTOS_TBL_MANTENIMIENTOS1`
    FOREIGN KEY (`ID_MANTENIMIENTO`)
    REFERENCES `bd_rutinas`.`TBL_MANTENIMIENTOS` (`ID_MANTENIMIENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_rutinas`.`TBL_COMENTARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_rutinas`.`TBL_COMENTARIOS` (
  `ID_COMENTARIO` INT NOT NULL,
  `ID_DATO_INSERTADO` INT NOT NULL,
  `ID_EMPLEADO` INT NOT NULL,
  `ID_COMENTARIO_SUPERIOR` INT NULL,
  `CONTENIDO_COMENTARIO` VARCHAR(300) NULL,
  INDEX `fk_TBL_COMENTARIOS_TBL_MASTER1_idx` (`ID_DATO_INSERTADO` ASC) VISIBLE,
  PRIMARY KEY (`ID_COMENTARIO`),
  INDEX `fk_TBL_COMENTARIOS_TBL_EMPLEADOS1_idx` (`ID_EMPLEADO` ASC) VISIBLE,
  INDEX `fk_TBL_COMENTARIOS_TBL_COMENTARIOS1_idx` (`ID_COMENTARIO_SUPERIOR` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_COMENTARIOS_TBL_MASTER1`
    FOREIGN KEY (`ID_DATO_INSERTADO`)
    REFERENCES `bd_rutinas`.`TBL_MASTER` (`ID_DATO_INSERTADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_COMENTARIOS_TBL_EMPLEADOS1`
    FOREIGN KEY (`ID_EMPLEADO`)
    REFERENCES `bd_rutinas`.`TBL_EMPLEADOS` (`ID_EMPLEADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_COMENTARIOS_TBL_COMENTARIOS1`
    FOREIGN KEY (`ID_COMENTARIO_SUPERIOR`)
    REFERENCES `bd_rutinas`.`TBL_COMENTARIOS` (`ID_COMENTARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bd_whatsapp` ;

-- -----------------------------------------------------
-- Table `bd_whatsapp`.`tbl_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_whatsapp`.`tbl_usuarios` (
  `codigo_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(300) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `url_imagen_perfil` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`codigo_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_whatsapp`.`tbl_contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_whatsapp`.`tbl_contactos` (
  `codigo_usuario` INT(11) NOT NULL,
  `codigo_usuario_contacto` INT(11) NOT NULL,
  INDEX `fk_tbl_amigos_tbl_usuarios_idx` (`codigo_usuario` ASC) VISIBLE,
  INDEX `fk_tbl_amigos_tbl_usuarios1_idx` (`codigo_usuario_contacto` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_amigos_tbl_usuarios`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `bd_whatsapp`.`tbl_usuarios` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_amigos_tbl_usuarios1`
    FOREIGN KEY (`codigo_usuario_contacto`)
    REFERENCES `bd_whatsapp`.`tbl_usuarios` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_whatsapp`.`tbl_mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_whatsapp`.`tbl_mensajes` (
  `codigo_mensaje` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo_usuario_emisor` INT(11) NOT NULL,
  `codigo_usuario_receptor` INT(11) NOT NULL,
  `mensaje` VARCHAR(1000) NOT NULL,
  `hora_mensaje` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_mensaje`),
  INDEX `fk_tbl_comentarios_tbl_usuarios1_idx` (`codigo_usuario_emisor` ASC) VISIBLE,
  INDEX `fk_tbl_mensajes_tbl_usuarios1_idx` (`codigo_usuario_receptor` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_comentarios_tbl_usuarios1`
    FOREIGN KEY (`codigo_usuario_emisor`)
    REFERENCES `bd_whatsapp`.`tbl_usuarios` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_mensajes_tbl_usuarios1`
    FOREIGN KEY (`codigo_usuario_receptor`)
    REFERENCES `bd_whatsapp`.`tbl_usuarios` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
