DELIMITER //
CREATE PROCEDURE Add_Item_Master(
   IN _ID_EQUIPO INTEGER,
   IN _ID_COMPONENTE INTEGER,
   IN _ID_EMPLEADO INTEGER,
   IN _SUBTIPO_BOOLEANO VARCHAR(10),
   IN _SUBTIPO_LISTA VARCHAR(10),
   IN _SUBTIPO_VALOR_NUMERO INTEGER,
   IN _DATO_NUMERICO_OBTENIDO VARCHAR(45)
)
BEGIN 
INSERT INTO tbl_master(ID_EQUIPO, ID_COMPONENTE_FINAL,ID_EMPLEADO,SUBTIPO_VALOR_BOOLEANO, SUBTIPO_VALOR_LISTA, SUBTIPO_VALOR_NUMERO, DATO_NUMERICO_OBTENIDO )
 VALUES (_ID_EQUIPO, _ID_COMPONENTE, _ID_EMPLEADO, _SUBTIPO_BOOLEANO, _SUBTIPO_LISTA, _SUBTIPO_VALOR_NUMERO, _DATO_NUMERICO_OBTENIDO);
END
//

CALL Add_Item_Master(25, 56, 2, '3 - 1', '2 - 1', 7, 65865);